### ISSUE TITLE
Incorrect typing of debug in the npm package

### ISSUE THREAD

**Issue by rickythefox** [nknapp/dom-preview#1]
In the npm package in `/dom-preview/dist/index.d.mts` we have 
```typescript
declare function debug(alias: string | undefined): void;
```

which results in a linter error when no argument is passed:
![image](https://github.com/nknapp/dom-preview/assets/1675955/4e770f39-12e4-4c3c-977f-627513366f2d)

The definition in this repo in `packages/dom-preview/src/debug.ts` is correct though (optional parameter). Maybe it's some packaging issue?

Setting strict to false in tsconfig resolves this but is obviously not a good solution.

Edit: interestingly enough building the package locally generates correct type declarations. Maybe the package in npm was built incorrectly?

**Comment by nknapp** [comment]
This error was already fixed, just not published. I haven't set up an automatic publishing workflow yet.

I published the current version as 0.6.1. Should be fine now.
